version: "3"

networks:
  smarthome:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "6080:80/tcp"
      - "6443:443/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PH_WEBPASSWORD}
    volumes:
       - '${DATADIR}/pihole/etc-pihole/:/etc/pihole/'
       - '${DATADIR}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 46.182.19.48
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:2.6.1
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ${DATADIR}/loki/config:/etc/loki
      - ${DATADIR}/loki/data:/data/loki
    command: --config.file=/etc/loki/loki-config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

